# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Glogovetan Claudiu
title: double C (Consultant and Contractor)
email: gadevelopment@outlook.com
website: https://justimplementit.blogspot.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: gaclaudiu
github_username:  gaclaudiu
stackoverflow_username: "494700"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: claudiuglogovetan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Claudiu and I love building stuff using technology.

  I am most skilled in Microsoft shop verticals with focus on distributed systems and cloud.

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FinClusive
        link: finclusive.com
        # link_text: boringcompany.com
        sub_title: Head of Engineering; Principal Architect
        caption: April 2018 - Present
        quote: >
          Getting shit done
        description: | # this will include new lines to allow paragraphs
            Building result oriented teams to help business grow.
            Focus on business and people growht with an eye on the balance between this two.

      - layout: left
        title: Recognos
        link: www.recognos.com
        # link_text: boringcompany.com
        sub_title: Software Architect;Technical Lead
        caption: Oct 2017 - Present; July 2015 - March 2016
        quote: >
          Getting shit done
        description: | # this will include new lines to allow paragraphs
            Leading teams with the goal of delivering project in financial sector.

      - layout: left
        title: Self Employed
        #link: www.recognos.com
        # link_text: boringcompany.com
        sub_title: Contractor
        caption: Jan 2017 - October 2017
        quote: >
          Getting shit done
        description: | # this will include new lines to allow paragraphs
            First steps taken into seeing what a contractor life looks like in IT industry.
      - layout: left
        title: Darwin (Thomsons Online Benefits)
        link: www.darwin.com
        # link_text: boringcompany.com
        sub_title:  Lead Engineer; Senior Software Engineer
        caption: March 2016 - January 2017; February 2014 - July 2015
        quote: >
          Getting shit done
        description: | # this will include new lines to allow paragraphs
            I was leading a new create team which had the goal to build a public API of the platform in order to make integrations smotter.

      - layout: left
        title: IQuest (now a Nagarro company)
        link: https://www.nagarro.com/en/news-events/nagarro-holding-and-iquest-group-join-forces-in-romania
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer; Software Engineer
        caption: July 2007 - April 2011
        quote: >
          First steps in the IT industry
        description: | # this will include new lines to allow paragraphs
            Learned a lot and worked on several project from different business domains as : pharma , automotive, banking, fashion and airline industry.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Babes-Bolyai University
        link: https://www.ubbcluj.ro/en/
        caption: 2004 - 2008
        sub_title: BSc Computer Science
        quote: >
          The University of Cluj, which is now being established, can avoid from the very beginning all the shortcomings that have accumulated over time, 
          for various reasons, in other older universities; we must secure for it all possibilities of development towards becoming a model of 
          Romanian University.
        description: | # this will include new lines to allow paragraphs
            During my time at Babes-Bolyai I polished my key skills  and learned new one to help me drive better what I would like do to with my professional career.
        
      - layout: left
        title: National College "Inochentie Micu Clain" 
        link: http://www.imclain.ro/
        caption: 2000 - 2004
        sub_title: Mathematics and Computer Science
        quote: >
          In the 250 years of existence of the Romanian schools in Blaj, despite the evolutions and dynamics from the political, social, economic and 
          cultural level, the National College "Inochentie Micu Clain" has constantly established itself as a factor of authentic patriotic education, 
          as a focus of culture and Romanian civilization. In such a context, the teaching staff of the National College "Inochentie Micu Clain" Blaj 
          assumes the responsibility to continue and develop the traditions of Blaj schools, in order to achieve a quality education, which facilitates 
          the successful integration of graduates in various forms higher education and the domestic and international labor market, thus ensuring a 
          European dimension in education.
        description: | # this will include new lines to allow paragraphs
            During my time at National College "Inochentie Micu Clain" I got my first touch on what programming is and what computers can do.

# Footer
footer_show_references: true
references_title: References or detailed resume on request 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
